apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sdhb8sej1-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:cdbd68144a93ee6d5a2a591ce861c911fe846ca4@sha256:e3661286135a0f3b4ac855cfa4beda5839f048d0d9a34bef436331c82b0d2a39
          name: container-image
